### ISSUE TITLE
Can I compile it？

### ISSUE THREAD

**Issue by sikenali** [rykdesjardins/litemail#1]
update readme？

**Comment by rykdesjardins** [comment]
Hi @jingle0927 ,

To be honest I didn't expect anyone to want to clone this repo hehe. It doesn't really do anything yet. It only contains a login page, outputs in the terminal and Inspector console, and login with GMail. 

I will still update the README as soon as possible to include more information about how the app is built and how to compile it.

On Linux (and probably Mac), first thing is to install the nodejs packages using `npm install`. Then, simply run `npm run debug` to compile and run the desktop app. I've not used Windows a while so not sure what's the procedure but it's probably similar if not the same. 

Let me know if you have any other question,

Cheers.
